logging:
  level:
    org.springframework.web: WARN
    com.danielctrenado: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/danielctrenado
    username: '{cipher}2e15b7b439951d2d2f2769caca6135451fdadd9c7cb6127f95f748787508af0a'
    password: '{cipher}fe8155c9ade57c12e524cecbbc55c211a22a7d71f9d77da34cbbad7bf7a9c22ac616d3d03c220b230049732e0b566854'
  jpa:
    properties:
      hibernate.default_schema: orderschema


#####################################################################################
#
# management
#
#####################################################################################
management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always
      circuitbreakers:
        enabled: true

##########################################
#
# resilience
#
##########################################
resilience4j:
  circuitbreaker:
    instances:
      order-customer:
        sliding-window-type: COUNT_BASED
        # Trigger Circuit Breaker if at least “failure-rate-threshold” of requests have failed.
        failure-rate-threshold: 10
        # Records at least “minimum-number-of-calls” requests in the last “sliding-window-size” seconds before calculating the failure rate.
        minimum-number-of-calls: 1
        # After ”wait-duration-in-open-state” seconds, Circuit Breaker will automatically transition from open to half-open state.
        automatic-transition-from-open-to-half-open-enabled: true
        # If triggered, wait at least “wait-duration-in-open-state” seconds before allowing more calls.
        wait-duration-in-open-state: 20s
        # After “wait-duration-in-open-state” time has passed, allow another “permitted-number-of-calls-in-half-open-state” requests and wait for them to calculate the failure rate again.
        permitted-number-of-calls-in-half-open-state: 2
        # Record the result of the last “sliding-window-size” seconds.
        sliding-window-size: 2
        register-health-indicator: true
